"""add status to schedules

Revision ID: 32296570c158
Revises: c84aa385a4ad
Create Date: 2026-09-02 14:50:36.441125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32296570c158'
down_revision: Union[str, Sequence[str], None] = 'c84aa385a4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'schedules',
    sa.Column(
        'status',
        sa.String(),
        nullable=False,
        server_default='inayofuata'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'status')
    # ### end Alembic commands ###
