"""Add status to activities

Revision ID: c84aa385a4ad
Revises: 08714d0e854c
Create Date: 2026-08-31 22:51:10.674275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84aa385a4ad'
down_revision: Union[str, Sequence[str], None] = '08714d0e854c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'activities',
    sa.Column(
        'hali',
        sa.String(),
        nullable=False,
        server_default='haijakamilika'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'hali')
    # ### end Alembic commands ###
